before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: false
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_cs_fixer:
        enabled: false
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
    sensiolabs_security_checker: true